### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by KH-88** [osohotwateriot/no.osoincharge#1]
Hi,

Good work on the app! :)
Are there any plans on adding holiday/sleep mode and high need (24h) to the app later? 

K

**Comment by osohotwateriot** [comment]
Hello,

I have taken into account your feature request and you can expect the new functionalities for sleep mode and high demand next week.

**Comment by osohotwateriot** [comment]
Hello,

The sleep mode and high demand are added as a Flow action in the latest version of the application. I am closing the topic.
