### ISSUE TITLE
Incorrect capability name for setting temperature

### ISSUE THREAD

**Issue by frodeheg** [osohotwateriot/no.osoincharge#3]
The temperature  settings for the water heating does not follow the [standard guidelines set by Athom](https://apps.developer.homey.app/the-basics/devices/capabilities#thermostat).

The capability name 'water_heater_current_set_point' should be renamed into 'target_temperature' and be made writeable

With this you will get a [thermostat capability](https://apps.developer.homey.app/the-basics/devices/capabilities#thermostat) that you can easily change and read temperature for.

**Comment by osohotwateriot** [comment]
Hello,

The target temperature of the water heaters was implemented this way because it is managed by the different modes - high demand/sleep mode and optimization mode. The different modes control the target temperature of the water heater.

I will implement an option to set the current target temperature on the water heaters but it will be overriden at a given point in time if any of the modes above are active.

**Comment by frodeheg** [comment]
That sounds sensible. Høiax water heaters also override the target temperature in case the mode is "legionella prevention program", but most of the time the target temperature is the actual target.

**Comment by osohotwateriot** [comment]
The implementation is done in version 1.0.5 and is currently awaiting for certification.

**Comment by frodeheg** [comment]
This is awsome, thank you. For price control, I think it's perfect to use the target temperature (not on/off), then you can set for example 55 degrees Celsius when it's expensive and 85 degrees Celsius when it's cheap. Then you have hot water all the time but make a buffer when it's cheap.

**Comment by frodeheg** [comment]
I see the maximum setting for temperature is only 75 degrees celsius.

Does the boost mode increase the temperature further? If so, then it's a bit unfortunate that they removed the highest part of the temperature range from the temperature API endpoint.

I mean, if you want a simple interface (thermostat) to set all temperatures then you would have to call the boost function automatically when adjusting the thermostat above 75 degrees, which seems like a stupid way to make the API.

My Høiax connected heater can be set to 85 degrees celsius, I suppose the OSO one can reach this temperature too, can't it?

**Comment by osohotwateriot** [comment]
The temperature for boost mode is 75 degrees as well.
The same applies for setting the profile - 75 degrees is the maximum that can be set at the moment. 
When optimization mode is set to Auto it is the same - device temperature is automatically managed and the maximum is 75 degrees.

**Comment by frodeheg** [comment]
Oh well, less hot water then, but on the bright side you lose less energy to the environment.

I measured the leakage heat to be 1.58W per degree Celsius difference between the environment and my tank (187l tank), so that's a saving of 15.8W constantly
