### ISSUE TITLE
Incorrect power usage

### ISSUE THREAD

**Issue by mgrendal** [osohotwateriot/no.osoincharge#4]
The app reports that my 300 liter water heater almost constantly uses exactly 3000 watts, with just a few sporadic dips. When I check the OSO API, "actualLoad" reports something like "0.0117865" kW when not heating, and around "2.4602468" kW when heating. Is it possible to fix this?

**Comment by osohotwateriot** [comment]
Hello,

The issue should be resolved now. Can you confirm and close this issue if that is the case for you?

**Comment by mgrendal** [comment]
This seems to be fixed now, thanks!
